### ISSUE TITLE
Postgres version 12

### ISSUE THREAD

**Issue by gloomytree** [foxcris/docker-postgresql#1]
Hi, 

the docker hub repo publishes two tags, 9.5 and 12. Both tags feature postgresql version 9.5.

Is this intentional? I had hopes that the 12 tag features postgresql 12. Atlassian Jira does not support 9.5 any longer =)

**Comment by foxcris** [comment]
hi,

sorry. That was not intentional. Now the image should be created and tagged correctly.

**Comment by gloomytree** [comment]
Awesome, ty for the really quick fix. I will try this tomorrow.
